### ISSUE TITLE
DeprecationWarning("This one won't work currently")

### ISSUE THREAD

**Issue by nil123532** [metadriverse/pvp#8]
Traceback (most recent call last):
  File "/home/nilesh/miniconda3/envs/pvp/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/nilesh/miniconda3/envs/pvp/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/nilesh/Desktop/new_folder/pvp/pvp/experiments/metadrive/train_pvp_metadrive.py", line 8, in <module>
    from pvp.experiments.metadrive.human_in_the_loop_env import HumanInTheLoopEnv
  File "/home/nilesh/Desktop/new_folder/pvp/pvp/experiments/metadrive/human_in_the_loop_env.py", line 6, in <module>
    from metadrive.engine.core.onscreen_message import ScreenMessage
  File "/home/nilesh/miniconda3/envs/pvp/lib/python3.7/site-packages/metadrive/__init__.py", line 11, in <module>
    _module = loader.find_module(module_name).load_module(module_name)
  File "/home/nilesh/miniconda3/envs/pvp/lib/python3.7/site-packages/metadrive/component/sensors/rgb_depth_camera.py", line 4, in <module>
    class RGBDepthCamera(DepthCamera):
  File "/home/nilesh/miniconda3/envs/pvp/lib/python3.7/site-packages/metadrive/component/sensors/rgb_depth_camera.py", line 8, in RGBDepthCamera
    raise DeprecationWarning("This one won't work currently")
DeprecationWarning: This one won't work currently

why do i get this error when trying to run pvp with metadrive with keyboard?

**Comment by neugzy** [comment]
When i try to run pvp with metadrive with keyboard, i always get the following info:
[INFO] Another instance of this program is already running. Wait for the asset pulling finished from another program...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
[INFO] Assets not pulled yet. Waiting for 10 seconds...
...
So, is this a error? Or do I really need to wait for how long?

**Comment by neugzy** [comment]
> When i try to run pvp with metadrive with keyboard, i always get the following info: [INFO] Another instance of this program is already running. Wait for the asset pulling finished from another program... [INFO] Assets not pulled yet. Waiting for 10 seconds... [INFO] Assets not pulled yet. Waiting for 10 seconds... [INFO] Assets not pulled yet. Waiting for 10 seconds... [INFO] Assets not pulled yet. Waiting for 10 seconds... ... So, is this a error? Or do I really need to wait for how long?

Oh, i have sovled this problem. Just need run "python -m metadrive.pull_asset" in your environment.
科学上网，并运行“python -m metadrive.pull_asset”指令，拉取asset.zip文件

**Comment by pengzhenghao** [comment]
Thank you so much for reporting! Seems like some metadrive pull asset issue. `python -m metadrive.pull_asset` is definetly a good solution!
